config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  root to: 'home#index'

  resources :users, controller: 'home' ,except: :index
  get '/all_user', to: 'home#all_users'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  
  validates :body, presence: true
  validates :title, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments , dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true ,uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @name = 'Haider'
  end

  def new
    @user = User.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email))
    respond_to do |format|
      @result = @user.save
      format.js
    end
  end

  def all_users
    @users = User.all
    respond_to do |format|
      format.js
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_form.html.erb
<h1 align="center"> Create a User </h1>

<%= form_with model: @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br><br>
  <%= f.label :email %>
  <%= f.text_field :email %>
<br><br>
  <%= f.submit "Create" %>
<% end %>
<br><br>

<%=link_to 'Back', root_path%>

app/views/home/_list.html.erb
<h1 align="center"> All Users </h1>

<ul>
	<% @users.each do |user|%>
	<li>
		<%= link_to user.name, user_path(user)%>
	</li>
	<%end%>
</ul>

<%= link_to 'Back', root_path%>

app/views/home/all_users.html.erb
<h1 align="center"> All Users </h1>

<ul>
	<% @users.each do |user|%>
	<li>
		<%= link_to user.name, user_path(user)%>
	</li>
	<%end%>
</ul>

<%= link_to 'Back', root_path%>

app/views/home/all_users.js.erb
$('#dynamic-user-area').html("<%= j render 'list' %>");

app/views/home/create.js.erb
<% if @result %>
  $('#dynamic-user-area').html('<p> User added Successfully</p>');
<% else %>
  $('#dynamic-user-area').html('<p> Error Occured!</p>');
<% end %>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">My App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
    	<% if person_signed_in? %>
	      <li class="nav-item active">
	        <!-- <a class="nav-link" href="#">Logout <span class="sr-only">(current)</span></a> -->
	        <%= link_to "Logout", destroy_person_session_path,method: :delete,class: 'nav-link' %>
	      </li>
      <% else %>
      	<li class="nav-item">	   
	        <%= link_to 'Login',new_person_session_path,class: 'nav-link' %>
	    </li>
	    <li class="nav-item">	   
	        <%= link_to 'Register',new_person_registration_path,class: 'nav-link' %>
	    </li>	    
      <% end %>      
    </ul>
  </div>
</nav>

<% if person_signed_in? %>
	<h1 align="center">Home#index</h1>
	<h2 align="center">Welcome <%= @name %> to  Ruby on Rails</h2>
	<p> What you want to do? </p>
	<br>
	<%= link_to 'Create User', new_user_path, remote: true%>
	<%= link_to 'List All Users', all_user_path, remote: true%>

	<div id="dynamic-user-area">
		
	</div>
<% else %>
<h1>Please Sign In first!</h1>
<% end %>

app/views/home/new.html.erb
<h1 align="center"> Create a User </h1>

<%= form_with model: @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br><br>
  <%= f.label :email %>
  <%= f.text_field :email %>
<br><br>
  <%= f.submit "Create" %>
<% end %>
<br><br>

<%=link_to 'Back', root_path%>

app/views/home/new.js.erb
$('#dynamic-user-area').html("<%= j render 'form' %>");

app/views/home/show.html.erb
<h1 align="center">Home#show</h1>
<h2 align="center">Welcome <%= @user.name %> to  Ruby on Rails</h2>
<%= link_to 'Back', root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>